https://www.perplexity.ai/search/66a9bb20-44c6-46c5-93f4-bc92820868a3

In [1]:
import yfinance as yf
import pandas as pd

from pandas import DataFrame
start_date = '2024-01-01'
end_date = '2025-01-01'

tickers = ['2330.TW', '2303.TW', '2454.TW', '2317.TW']
all_data:dict[str:DataFrame]= {ticker: yf.download(ticker,start=start_date, end=end_date, interval='1d',auto_adjust=False) for ticker in tickers }
price_df = pd.DataFrame({key:dataframe['Adj Close'][key] for key,dataframe in all_data.items()})
price_df1 = price_df.rename(columns={'2330.TW':'台積電','2303.TW':'聯電','2454.TW':'聯發科','2317.TW':'鴻海'})
price_df1

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                    台積電         聯電          聯發科          鴻海
Date
2024-01-02   570.360229  46.182152   881.073242   98.787247
2024-01-03   555.932861  45.025372   855.925415   98.316833
2024-01-04   557.856506  45.203335   855.556580   97.846420
2024-01-05   554.009216  45.203335   849.103027   97.846420
2024-01-08   560.741943  44.936390   848.181152   95.494339
...                 ...        ...          ...         ...
2024-12-25  1061.257202  41.378731  1328.683472  179.964066
2024-12-26  1061.257202  41.049957  1338.106812  180.929031
2024-12-27  1066.147827  40.956017  1347.530029  179.964066
2024-12-30  1066.147827  40.486340  1338.106812  178.516632
2024-12-31  1051.475952  40.439373  1333.395142  177.551682

[242 rows x 4 columns]

In [2]:
price_df2 = price_df1.groupby(price_df1.index.month).agg([("平均","mean"),("最高","max"),("最低","min")])
price_df2.index = "2024- "+ price_df2.index.astype(str) + "月份"
price_df2

                    台積電                                   聯電             \
                     平均           最高           最低         平均         最高
Date
2024- 1月份    581.290017   623.260376   554.009216  44.643149  46.538082
2024- 2月份    651.819101   671.351562   604.024048  43.286782  43.824100
2024- 3月份    735.112813   758.555481   662.695129  45.796558  47.427914
2024- 4月份    761.406210   792.376587   717.004150  45.283423  47.338928
2024- 5月份    800.678045   845.523743   745.993591  47.504761  50.364349
2024- 6月份    892.877750   951.616821   810.736511  49.746152  51.343163
2024- 7月份    966.213725  1047.651489   896.324097  49.499701  51.946510
2024- 8月份    908.141005   943.856445   790.588806  51.141651  52.604061
2024- 9月份    921.639767   988.989136   862.372314  50.960184  52.040447
2024- 10月份  1014.066477  1057.195312   947.091064  48.045702  50.443539
2024- 11月份  1009.219055  1062.067139   970.476013  42.595423  44.290741
2024- 12月份  1045.363869  1066.147827  1008.476807  40.695561  42.083248

                               聯發科                                    鴻海  \
                   最低           平均           最高           最低          平均
Date
2024- 1月份   42.800797   854.009311   890.590210   810.381714   95.490065
2024- 2月份   42.711819   932.999221  1051.006958   857.400513   96.616099
2024- 3月份   42.978764  1074.494484  1133.981323  1018.739380  119.933545
2024- 4月份   43.334698   994.261899  1106.323120   890.590210  142.441805
2024- 5月份   44.758423  1070.493400  1207.736084   921.935974  160.839328
2024- 6月份   47.605877  1257.229595  1382.904053  1133.981323  184.229554
2024- 7月份   46.967911  1255.696086  1375.799927  1149.641113  201.565271
2024- 8月份   46.920944  1110.491572  1182.622559   933.847778  174.042756
2024- 9月份   50.067795  1093.572510  1196.757446  1041.273315  173.257634
2024- 10月份  45.230099  1207.916626  1258.008789  1140.217773  198.247422
2024- 11月份  40.909050  1201.693493  1234.450684  1163.776001  200.779522
2024- 12月份  38.936401  1299.556979  1347.530029  1229.739014  182.179078


                    最高          最低
Date
2024- 1月份    98.787247   92.765930
2024- 2月份    97.375999   95.023926
2024- 3月份   146.299225   95.964760
2024- 4月份   149.592117  132.657166
2024- 5月份   174.524139  144.887970
2024- 6月份   204.630737  160.882080
2024- 7月份   218.562256  185.271317
2024- 8月份   195.403351  157.770111
2024- 9月份   184.306366  163.077362
2024- 10月份  208.430237  180.446548
2024- 11月份  212.290054  188.648666
2024- 12月份  193.955917  174.656815